version: '3.8'


services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: group_1
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    expose:
      - "5432"
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "./postgres:/var/lib/postgresql/data"
volumes:
  postgres: ~
