version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - '9042:9042'
    volumes:
      - cass_data:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=cassandra
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=32M
      - MAX_HEAP_SIZE=512M
      - CLIENT_TIMEOUT=20
    restart: always

volumes:
  cass_data: